/*
 * Carvajal Sigo-Facturizate
 *
 * Este es un ejemplo de como luciría la Api de Integración entre Facturizate y SIGO.
 *
 * OpenAPI spec version: beta
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace IO.Swagger.Models
{
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class AuthorizedCfdi :  IEquatable<AuthorizedCfdi>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="AuthorizedCfdi" /> class.
        /// </summary>
        /// <param name="Id">Id.</param>
        /// <param name="IsValidRfc">Indicates whether or not it exists in SIGO.</param>
        /// <param name="AssociateCertNumber">This in order to be able to carry out the process of letterhead of the documents.</param>
        public AuthorizedCfdi(long? Id = null, bool? IsValidRfc = null, string AssociateCertNumber = null)
        {
            this.Id = Id;
            this.IsValidRfc = IsValidRfc;
            this.AssociateCertNumber = AssociateCertNumber;
            
        }

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [DataMember(Name="id")]
        public long? Id { get; set; }

        /// <summary>
        /// Indicates whether or not it exists in SIGO
        /// </summary>
        /// <value>Indicates whether or not it exists in SIGO</value>
        [DataMember(Name="isValidRfc")]
        public bool? IsValidRfc { get; set; }

        /// <summary>
        /// This in order to be able to carry out the process of letterhead of the documents
        /// </summary>
        /// <value>This in order to be able to carry out the process of letterhead of the documents</value>
        [DataMember(Name="associateCertNumber")]
        public string AssociateCertNumber { get; set; }


        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class AuthorizedCfdi {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  IsValidRfc: ").Append(IsValidRfc).Append("\n");
            sb.Append("  AssociateCertNumber: ").Append(AssociateCertNumber).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            if (obj.GetType() != GetType()) return false;
            return Equals((AuthorizedCfdi)obj);
        }

        /// <summary>
        /// Returns true if AuthorizedCfdi instances are equal
        /// </summary>
        /// <param name="other">Instance of AuthorizedCfdi to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(AuthorizedCfdi other)
        {

            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    this.Id == other.Id ||
                    this.Id != null &&
                    this.Id.Equals(other.Id)
                ) && 
                (
                    this.IsValidRfc == other.IsValidRfc ||
                    this.IsValidRfc != null &&
                    this.IsValidRfc.Equals(other.IsValidRfc)
                ) && 
                (
                    this.AssociateCertNumber == other.AssociateCertNumber ||
                    this.AssociateCertNumber != null &&
                    this.AssociateCertNumber.Equals(other.AssociateCertNumber)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                if (this.Id != null)
                    hash = hash * 59 + this.Id.GetHashCode();
                if (this.IsValidRfc != null)
                    hash = hash * 59 + this.IsValidRfc.GetHashCode();
                if (this.AssociateCertNumber != null)
                    hash = hash * 59 + this.AssociateCertNumber.GetHashCode();
                return hash;
            }
        }

        #region Operators

        public static bool operator ==(AuthorizedCfdi left, AuthorizedCfdi right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(AuthorizedCfdi left, AuthorizedCfdi right)
        {
            return !Equals(left, right);
        }

        #endregion Operators

    }
}
