/*
 * Carvajal Sigo-Facturizate
 *
 * Este es un ejemplo de como luciría la Api de Integración entre Facturizate y SIGO.
 *
 * OpenAPI spec version: beta
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace IO.Swagger.Models
{
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class CfdiCredential :  IEquatable<CfdiCredential>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CfdiCredential" /> class.
        /// </summary>
        /// <param name="Id">Id.</param>
        /// <param name="UserCfd">null.</param>
        /// <param name="PasswordCfdi">This in order to be able to carry out the process of letterhead of the documents.</param>
        /// <param name="TokenCfdi">Thi is the token used to execute the web Service for letterhead the documents..</param>
        public CfdiCredential(long? Id = null, string UserCfd = null, string PasswordCfdi = null, string TokenCfdi = null)
        {
            this.Id = Id;
            this.UserCfd = UserCfd;
            this.PasswordCfdi = PasswordCfdi;
            this.TokenCfdi = TokenCfdi;
            
        }

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [DataMember(Name="id")]
        public long? Id { get; set; }

        /// <summary>
        /// null
        /// </summary>
        /// <value>null</value>
        [DataMember(Name="userCfd")]
        public string UserCfd { get; set; }

        /// <summary>
        /// This in order to be able to carry out the process of letterhead of the documents
        /// </summary>
        /// <value>This in order to be able to carry out the process of letterhead of the documents</value>
        [DataMember(Name="passwordCfdi")]
        public string PasswordCfdi { get; set; }

        /// <summary>
        /// Thi is the token used to execute the web Service for letterhead the documents.
        /// </summary>
        /// <value>Thi is the token used to execute the web Service for letterhead the documents.</value>
        [DataMember(Name="tokenCfdi")]
        public string TokenCfdi { get; set; }


        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class CfdiCredential {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  UserCfd: ").Append(UserCfd).Append("\n");
            sb.Append("  PasswordCfdi: ").Append(PasswordCfdi).Append("\n");
            sb.Append("  TokenCfdi: ").Append(TokenCfdi).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            if (obj.GetType() != GetType()) return false;
            return Equals((CfdiCredential)obj);
        }

        /// <summary>
        /// Returns true if CfdiCredential instances are equal
        /// </summary>
        /// <param name="other">Instance of CfdiCredential to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(CfdiCredential other)
        {

            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    this.Id == other.Id ||
                    this.Id != null &&
                    this.Id.Equals(other.Id)
                ) && 
                (
                    this.UserCfd == other.UserCfd ||
                    this.UserCfd != null &&
                    this.UserCfd.Equals(other.UserCfd)
                ) && 
                (
                    this.PasswordCfdi == other.PasswordCfdi ||
                    this.PasswordCfdi != null &&
                    this.PasswordCfdi.Equals(other.PasswordCfdi)
                ) && 
                (
                    this.TokenCfdi == other.TokenCfdi ||
                    this.TokenCfdi != null &&
                    this.TokenCfdi.Equals(other.TokenCfdi)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                if (this.Id != null)
                    hash = hash * 59 + this.Id.GetHashCode();
                if (this.UserCfd != null)
                    hash = hash * 59 + this.UserCfd.GetHashCode();
                if (this.PasswordCfdi != null)
                    hash = hash * 59 + this.PasswordCfdi.GetHashCode();
                if (this.TokenCfdi != null)
                    hash = hash * 59 + this.TokenCfdi.GetHashCode();
                return hash;
            }
        }

        #region Operators

        public static bool operator ==(CfdiCredential left, CfdiCredential right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(CfdiCredential left, CfdiCredential right)
        {
            return !Equals(left, right);
        }

        #endregion Operators

    }
}
