/*
 * Carvajal Sigo-Facturizate
 *
 * Este es un ejemplo de como luciría la Api de Integración entre Facturizate y SIGO.
 *
 * OpenAPI spec version: beta
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace IO.Swagger.Models
{
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class Complements :  IEquatable<Complements>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Complements" /> class.
        /// </summary>
        /// <param name="ComplementId">ComplementId.</param>
        /// <param name="ComplementName">ComplementName.</param>
        /// <param name="IsEnabled">IsEnabled.</param>
        /// <param name="ComplementType">ComplementType.</param>
        public Complements(long? ComplementId = null, string ComplementName = null, bool? IsEnabled = null, string ComplementType = null)
        {
            this.ComplementId = ComplementId;
            this.ComplementName = ComplementName;
            this.IsEnabled = IsEnabled;
            this.ComplementType = ComplementType;
            
        }

        /// <summary>
        /// Gets or Sets ComplementId
        /// </summary>
        [DataMember(Name="complementId")]
        public long? ComplementId { get; set; }

        /// <summary>
        /// Gets or Sets ComplementName
        /// </summary>
        [DataMember(Name="complementName")]
        public string ComplementName { get; set; }

        /// <summary>
        /// Gets or Sets IsEnabled
        /// </summary>
        [DataMember(Name="isEnabled")]
        public bool? IsEnabled { get; set; }

        /// <summary>
        /// Gets or Sets ComplementType
        /// </summary>
        [DataMember(Name="complementType")]
        public string ComplementType { get; set; }


        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class Complements {\n");
            sb.Append("  ComplementId: ").Append(ComplementId).Append("\n");
            sb.Append("  ComplementName: ").Append(ComplementName).Append("\n");
            sb.Append("  IsEnabled: ").Append(IsEnabled).Append("\n");
            sb.Append("  ComplementType: ").Append(ComplementType).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            if (obj.GetType() != GetType()) return false;
            return Equals((Complements)obj);
        }

        /// <summary>
        /// Returns true if Complements instances are equal
        /// </summary>
        /// <param name="other">Instance of Complements to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(Complements other)
        {

            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    this.ComplementId == other.ComplementId ||
                    this.ComplementId != null &&
                    this.ComplementId.Equals(other.ComplementId)
                ) && 
                (
                    this.ComplementName == other.ComplementName ||
                    this.ComplementName != null &&
                    this.ComplementName.Equals(other.ComplementName)
                ) && 
                (
                    this.IsEnabled == other.IsEnabled ||
                    this.IsEnabled != null &&
                    this.IsEnabled.Equals(other.IsEnabled)
                ) && 
                (
                    this.ComplementType == other.ComplementType ||
                    this.ComplementType != null &&
                    this.ComplementType.Equals(other.ComplementType)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                if (this.ComplementId != null)
                    hash = hash * 59 + this.ComplementId.GetHashCode();
                if (this.ComplementName != null)
                    hash = hash * 59 + this.ComplementName.GetHashCode();
                if (this.IsEnabled != null)
                    hash = hash * 59 + this.IsEnabled.GetHashCode();
                if (this.ComplementType != null)
                    hash = hash * 59 + this.ComplementType.GetHashCode();
                return hash;
            }
        }

        #region Operators

        public static bool operator ==(Complements left, Complements right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(Complements left, Complements right)
        {
            return !Equals(left, right);
        }

        #endregion Operators

    }
}
