/*
 * Carvajal Sigo-Facturizate
 *
 * Este es un ejemplo de como luciría la Api de Integración entre Facturizate y SIGO.
 *
 * OpenAPI spec version: beta
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace IO.Swagger.Models
{
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class PaperSheets :  IEquatable<PaperSheets>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PaperSheets" /> class.
        /// </summary>
        /// <param name="RfcEmitter">RfcEmitter.</param>
        /// <param name="SheetQuantity">SheetQuantity.</param>
        public PaperSheets(string RfcEmitter = null, int? SheetQuantity = null)
        {
            this.RfcEmitter = RfcEmitter;
            this.SheetQuantity = SheetQuantity;
            
        }

        /// <summary>
        /// Gets or Sets RfcEmitter
        /// </summary>
        [DataMember(Name="rfcEmitter")]
        public string RfcEmitter { get; set; }

        /// <summary>
        /// Gets or Sets SheetQuantity
        /// </summary>
        [DataMember(Name="sheetQuantity")]
        public int? SheetQuantity { get; set; }


        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class PaperSheets {\n");
            sb.Append("  RfcEmitter: ").Append(RfcEmitter).Append("\n");
            sb.Append("  SheetQuantity: ").Append(SheetQuantity).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            if (obj.GetType() != GetType()) return false;
            return Equals((PaperSheets)obj);
        }

        /// <summary>
        /// Returns true if PaperSheets instances are equal
        /// </summary>
        /// <param name="other">Instance of PaperSheets to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(PaperSheets other)
        {

            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    this.RfcEmitter == other.RfcEmitter ||
                    this.RfcEmitter != null &&
                    this.RfcEmitter.Equals(other.RfcEmitter)
                ) && 
                (
                    this.SheetQuantity == other.SheetQuantity ||
                    this.SheetQuantity != null &&
                    this.SheetQuantity.Equals(other.SheetQuantity)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                if (this.RfcEmitter != null)
                    hash = hash * 59 + this.RfcEmitter.GetHashCode();
                if (this.SheetQuantity != null)
                    hash = hash * 59 + this.SheetQuantity.GetHashCode();
                return hash;
            }
        }

        #region Operators

        public static bool operator ==(PaperSheets left, PaperSheets right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(PaperSheets left, PaperSheets right)
        {
            return !Equals(left, right);
        }

        #endregion Operators

    }
}
