/*
 * Carvajal Sigo-Facturizate
 *
 * Este es un ejemplo de como luciría la Api de Integración entre Facturizate y SIGO.
 *
 * OpenAPI spec version: beta
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace IO.Swagger.Models
{
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class Privileges :  IEquatable<Privileges>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Privileges" /> class.
        /// </summary>
        /// <param name="Priviledge">shows a priviledge as string with the following format [product].[country].[app].[priviledge].</param>
        public Privileges(string Priviledge = null)
        {
            this.Priviledge = Priviledge;
            
        }

        /// <summary>
        /// shows a priviledge as string with the following format [product].[country].[app].[priviledge]
        /// </summary>
        /// <value>shows a priviledge as string with the following format [product].[country].[app].[priviledge]</value>
        [DataMember(Name="priviledge")]
        public string Priviledge { get; set; }


        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class Privileges {\n");
            sb.Append("  Priviledge: ").Append(Priviledge).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            if (obj.GetType() != GetType()) return false;
            return Equals((Privileges)obj);
        }

        /// <summary>
        /// Returns true if Privileges instances are equal
        /// </summary>
        /// <param name="other">Instance of Privileges to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(Privileges other)
        {

            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    this.Priviledge == other.Priviledge ||
                    this.Priviledge != null &&
                    this.Priviledge.Equals(other.Priviledge)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                if (this.Priviledge != null)
                    hash = hash * 59 + this.Priviledge.GetHashCode();
                return hash;
            }
        }

        #region Operators

        public static bool operator ==(Privileges left, Privileges right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(Privileges left, Privileges right)
        {
            return !Equals(left, right);
        }

        #endregion Operators

    }
}
